### ISSUE TITLE
Configuration for rule "@typescript-eslint/consistent-type-imports" is invalid

### ISSUE THREAD

**Issue by joel-daros** [standard/eslint-config-standard-with-typescript#1121]
**What version of this package are you using?**
```
{
  "name": "functions",
  "scripts": {
    "lint": "eslint --fix --ext .ts ./src/",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "date-fns": "^2.29.3",
    "date-fns-tz": "^2.0.0",
    "firebase-admin": "^11.7.0",
    "firebase-functions": "^4.3.1",
    "nodemailer": "^6.9.1",
    "secure-compare": "^3.0.1"
  },
  "devDependencies": {
    "@types/nodemailer": "^6.4.7",
    "@typescript-eslint/eslint-plugin": "^5.43.0",
    "eslint": "^8.39.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-promise": "^6.1.1",
    "firebase-functions-test": "^3.1.0",
    "typescript": "^5.0.4"
  },
  "engines": {
    "node": "16"
  },
  "private": true
}
```

.eslintrc.js:
```javascript
module.exports = {
  env: {
    es2021: true,
    node: true,
  },
  extends: "standard-with-typescript",
  overrides: [],
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  rules: {},
};
```

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "outDir": "lib",
    "sourceMap": true,
    "target": "es2017",
    "baseUrl": "./",
    "typeRoots": ["node_modules/@types"]
  },
  "compileOnSave": true,
  "include": ["src"]
}
```

**What operating system, Node.js, and npm version?**
MacOS, Node 16, npm 9.6.5

**What happened?**
```shell
npm run lint

> lint
> eslint --fix ./src/**


Oops! Something went wrong! :(

ESLint: 8.39.0

Error: .eslintrc.js » eslint-config-standard-with-typescript#overrides[0]:
        Configuration for rule "@typescript-eslint/consistent-type-imports" is invalid:
        Value {"prefer":"type-imports","disallowTypeAnnotations":true,"fixStyle":"inline-type-imports"} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (/Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2027:23)
    at /Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2082:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2079:34)
    at ConfigValidator.validateConfigArray (/Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2205:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3962:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/xxx/Desenv/algarve/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3768:21)
    at FileEnumerator._iterateFilesWithFile (/Users/xxx/Desenv/algarve/functions/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/Users/xxx/Desenv/algarve/functions/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/Users/xxx/Desenv/algarve/functions/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
```

**What did you expect to happen?**
No error

**Are you willing to submit a pull request to fix this bug?**

**Comment by mightyiam** [comment]
@joel-daros is this still an issue, please?

Could you paste the output from `npm ls`, please?

**Comment by mightyiam** [comment]
Is there no error/warning anywhere? You're using an unsupported version:

```
├── @typescript-eslint/eslint-plugin@6.2.0
```
https://github.com/standard/eslint-config-standard-with-typescript/blob/a3dbd3b69e6480424551fb2cdea98b416596c954/package.json#L60

**Comment by mightyiam** [comment]
Would you mind providing a reproduction, please?

**Comment by matthew-dean** [comment]
I'm also seeing `Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid`. It appears `eslint-config-standard-with-typescript` is incompatible with latest `@typescript-eslint` parser / plugin. However, `@typescript-eslint/*` can't be rolled back because it would be incompatible with TypeScript 5.x.

**Comment by mightyiam** [comment]
@joel-daros if you happen to reproduce this, please reopen. Sorry to ask, but otherwise I wouldn't be able to help.
