### ISSUE TITLE
conflicting peer dependency

### ISSUE THREAD

**Issue by CCFenner** [standard/eslint-config-standard-with-typescript#1142]
**What version of this package are you using?**
`34.0.1`

**What operating system, Node.js, and npm version?**

**What happened?**

When I try to update `eslint-plugin-n` to v16, `npm install` fails:

```
npm WARN config init.author.name Use `--init-author-name` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-config-standard-with-typescript@34.0.1
npm ERR! Found: eslint-plugin-n@16.0.0
npm ERR! node_modules/eslint-plugin-n
npm ERR!   dev eslint-plugin-n@"16.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-n@"^15.0.0" from eslint-config-standard-with-typescript@34.0.1
npm ERR! node_modules/eslint-config-standard-with-typescript
npm ERR!   dev eslint-config-standard-with-typescript@"34.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-plugin-n@15.7.0
npm ERR! node_modules/eslint-plugin-n
npm ERR!   peer eslint-plugin-n@"^15.0.0" from eslint-config-standard-with-typescript@34.0.1
npm ERR!   node_modules/eslint-config-standard-with-typescript
npm ERR!     dev eslint-config-standard-with-typescript@"34.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by emrecancorapci** [comment]
Same here

```0 verbose cli G:\Windows\Programs\nodejs\node.exe C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.6
2 info using node@v18.14.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 6ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:F:\work\eneftimbu-frontend\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Emre\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Emre\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 17ms
17 timing npm:load:configload Completed in 18ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm i
21 verbose argv "i"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 6ms
24 timing npm:load:display Completed in 7ms
25 verbose logfile logs-max:10 dir:C:\Users\Emre\AppData\Local\npm-cache\_logs\2023-05-26T15_37_34_931Z-
26 verbose logfile C:\Users\Emre\AppData\Local\npm-cache\_logs\2023-05-26T15_37_34_931Z-debug-0.log
27 timing npm:load:logFile Completed in 21ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 52ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 timing idealTree:init Completed in 360ms
34 timing idealTree:userRequests Completed in 0ms
35 silly idealTree buildDeps
36 silly fetch manifest styled-components@^5.3.11
37 silly logfile done cleaning log files
38 http fetch GET 200 https://registry.npmjs.org/styled-components 50ms (cache hit)
39 silly fetch manifest react@^18.2.0
40 http fetch GET 200 https://registry.npmjs.org/react 24ms (cache hit)
41 silly fetch manifest react-dom@^18.2.0
42 http fetch GET 200 https://registry.npmjs.org/react-dom 17ms (cache hit)
43 silly fetch manifest react-is@>= 16.8.0
44 http fetch GET 200 https://registry.npmjs.org/react-is 32ms (cache hit)
45 silly fetch manifest @types/react@^18.2.7
46 http fetch GET 200 https://registry.npmjs.org/@types%2freact 10ms (cache hit)
47 silly fetch manifest @typescript-eslint/eslint-plugin@^5.59.7
48 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 24ms (cache hit)
49 silly fetch manifest @typescript-eslint/parser@^5.59.7
50 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 23ms (cache hit)
51 silly fetch manifest eslint@^8.41.0
52 http fetch GET 200 https://registry.npmjs.org/eslint 221ms (cache revalidated)
53 silly fetch manifest vite@^4.3.9
54 http fetch GET 200 https://registry.npmjs.org/vite 14ms (cache hit)
55 silly fetch manifest @types/node@>= 14
56 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 14ms (cache hit)
57 silly fetch manifest less@*
58 http fetch GET 200 https://registry.npmjs.org/less 13ms (cache hit)
59 silly fetch manifest sass@^1.62.1
60 http fetch GET 200 https://registry.npmjs.org/sass 8ms (cache hit)
61 silly fetch manifest stylus@*
62 http fetch GET 200 https://registry.npmjs.org/stylus 8ms (cache hit)
63 silly fetch manifest sugarss@*
64 http fetch GET 200 https://registry.npmjs.org/sugarss 7ms (cache hit)
65 silly fetch manifest postcss@^8.3.3
66 http fetch GET 200 https://registry.npmjs.org/postcss 10ms (cache hit)
67 silly fetch manifest terser@^5.4.0
68 http fetch GET 200 https://registry.npmjs.org/terser 8ms (cache hit)
69 silly placeDep ROOT @types/react@18.2.7 REPLACE for: eneftimbu@0.3.0 want: ^18.2.7
70 silly placeDep ROOT @typescript-eslint/eslint-plugin@5.59.7 REPLACE for: eneftimbu@0.3.0 want: ^5.59.7
71 silly fetch manifest @typescript-eslint/scope-manager@5.59.7
72 silly fetch manifest @typescript-eslint/type-utils@5.59.7
73 silly fetch manifest @typescript-eslint/utils@5.59.7
74 silly placeDep ROOT @typescript-eslint/parser@5.59.7 REPLACE for: eneftimbu@0.3.0 want: ^5.59.7
75 silly fetch manifest @typescript-eslint/types@5.59.7
76 silly fetch manifest @typescript-eslint/typescript-estree@5.59.7
77 silly placeDep ROOT eslint@8.41.0 REPLACE for: eneftimbu@0.3.0 want: ^8.41.0
78 silly fetch manifest @eslint/js@8.41.0
79 silly fetch manifest graphemer@^1.4.0
80 silly placeDep ROOT styled-components@5.3.11 REPLACE for: eneftimbu@0.3.0 want: ^5.3.11
81 silly placeDep ROOT vite@4.3.9 REPLACE for: eneftimbu@0.3.0 want: ^4.3.9
82 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fscope-manager 124ms (cache hit)
83 http fetch GET 200 https://registry.npmjs.org/@eslint%2fjs 155ms (cache hit)
84 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftype-utils 198ms (cache hit)
85 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree 231ms (cache hit)
86 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2futils 297ms (cache hit)
87 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypes 306ms (cache hit)
88 http fetch GET 200 https://registry.npmjs.org/graphemer 302ms (cache hit)
89 timing idealTree:#root Completed in 1076ms
90 timing idealTree:node_modules/@types/react Completed in 0ms
91 silly fetch manifest eslint@^6.0.0 || ^7.0.0 || ^8.0.0
92 silly placeDep node_modules/@typescript-eslint/eslint-plugin @typescript-eslint/scope-manager@5.59.7 OK for: @typescript-eslint/eslint-plugin@5.59.7 want: 5.59.7
93 silly fetch manifest @typescript-eslint/visitor-keys@5.59.7
94 silly placeDep ROOT @typescript-eslint/type-utils@5.59.7 OK for: @typescript-eslint/eslint-plugin@5.59.7 want: 5.59.7
95 silly placeDep ROOT @typescript-eslint/utils@5.59.7 REPLACE for: @typescript-eslint/eslint-plugin@5.59.7 want: 5.59.7
96 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fvisitor-keys 40ms (cache hit)
97 timing idealTree:node_modules/@typescript-eslint/eslint-plugin Completed in 75ms
98 silly placeDep ROOT @typescript-eslint/scope-manager@5.59.7 OK for: @typescript-eslint/parser@5.59.7 want: 5.59.7
99 silly placeDep ROOT @typescript-eslint/types@5.59.7 OK for: @typescript-eslint/parser@5.59.7 want: 5.59.7
100 silly placeDep ROOT @typescript-eslint/typescript-estree@5.59.7 OK for: @typescript-eslint/parser@5.59.7 want: 5.59.7
101 silly fetch manifest globby@^11.1.0
102 silly fetch manifest semver@^7.3.7
103 http fetch GET 200 https://registry.npmjs.org/globby 17ms (cache hit)
104 http fetch GET 200 https://registry.npmjs.org/semver 18ms (cache hit)
105 timing idealTree:node_modules/@typescript-eslint/parser Completed in 30ms
106 silly placeDep ROOT @typescript-eslint/visitor-keys@5.59.7 OK for: @typescript-eslint/scope-manager@5.59.7 want: 5.59.7
107 timing idealTree:node_modules/@typescript-eslint/scope-manager Completed in 1ms
108 timing idealTree:node_modules/@typescript-eslint/type-utils Completed in 1ms
109 timing idealTree:node_modules/@typescript-eslint/types Completed in 0ms
110 silly placeDep ROOT globby@11.1.0 OK for: @typescript-eslint/typescript-estree@5.59.7 want: ^11.1.0
111 silly fetch manifest array-union@^2.1.0
112 silly fetch manifest dir-glob@^3.0.1
113 silly placeDep node_modules/@typescript-eslint/typescript-estree semver@7.5.1 OK for: @typescript-eslint/typescript-estree@5.59.7 want: ^7.3.7
114 silly fetch manifest lru-cache@^6.0.0
115 http fetch GET 200 https://registry.npmjs.org/dir-glob 17ms (cache hit)
116 http fetch GET 200 https://registry.npmjs.org/lru-cache 17ms (cache hit)
117 http fetch GET 200 https://registry.npmjs.org/array-union 27ms (cache hit)
118 timing idealTree:node_modules/@typescript-eslint/typescript-estree Completed in 31ms
119 timing idealTree:node_modules/@typescript-eslint/utils Completed in 1ms
120 timing idealTree:node_modules/@typescript-eslint/visitor-keys Completed in 0ms
121 silly placeDep ROOT @eslint/js@8.41.0 OK for: eslint@8.41.0 want: 8.41.0
122 silly placeDep ROOT graphemer@1.4.0 OK for: eslint@8.41.0 want: ^1.4.0
123 timing idealTree:node_modules/eslint Completed in 4ms
124 timing idealTree:node_modules/@eslint/js Completed in 0ms
125 silly fetch manifest eslint-plugin-n@^15.0.0
126 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-n 112ms (cache revalidated)
127 silly fetch manifest eslint@^8.0.1
128 timing idealTree Completed in 1708ms
129 timing command:i Completed in 1718ms
130 verbose stack Error: could not resolve
130 verbose stack     at PlaceDep.failPeerConflict (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:503:25)
130 verbose stack     at new PlaceDep (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:157:21)
130 verbose stack     at #buildDepStep (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:933:18)
130 verbose stack     at async Arborist.buildIdealTree (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:196:7)
130 verbose stack     at async Promise.all (index 1)
130 verbose stack     at async Arborist.reify (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
130 verbose stack     at async Install.exec (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:147:5)
130 verbose stack     at async module.exports (C:\Users\Emre\AppData\Roaming\npm\node_modules\npm\lib\cli.js:89:5)
131 verbose cwd F:\work\eneftimbu-frontend
132 verbose Windows_NT 10.0.19045
133 verbose node v18.14.0
134 verbose npm  v9.6.6
135 error code ERESOLVE
136 error ERESOLVE could not resolve
137 error
138 error While resolving: [1meslint-config-standard-with-typescript[22m@[1m34.0.1[22m
138 error Found: [1meslint-plugin-n[22m@[1m16.0.0[22m[2m[22m
138 error [2mnode_modules/eslint-plugin-n[22m
138 error   [33mdev[39m [1meslint-plugin-n[22m@"[1m^16.0.0[22m" from the root project
138 error
138 error Could not resolve dependency:
138 error [35mpeer[39m [1meslint-plugin-n[22m@"[1m^15.0.0[22m" from [1meslint-config-standard-with-typescript[22m@[1m34.0.1[22m[2m[22m
138 error [2mnode_modules/eslint-config-standard-with-typescript[22m
138 error   [33mdev[39m [1meslint-config-standard-with-typescript[22m@"[1m^34.0.1[22m" from the root project
138 error
138 error Conflicting peer dependency: [1meslint-plugin-n[22m@[1m15.7.0[22m[2m[22m
138 error [2mnode_modules/eslint-plugin-n[22m
138 error   [35mpeer[39m [1meslint-plugin-n[22m@"[1m^15.0.0[22m" from [1meslint-config-standard-with-typescript[22m@[1m34.0.1[22m[2m[22m
138 error   [2mnode_modules/eslint-config-standard-with-typescript[22m
138 error     [33mdev[39m [1meslint-config-standard-with-typescript[22m@"[1m^34.0.1[22m" from the root project
138 error
138 error Fix the upstream dependency conflict, or retry
138 error this command with --force or --legacy-peer-deps
138 error to accept an incorrect (and potentially broken) dependency resolution.
139 error
139 error
139 error For a full report see:
139 error C:\Users\Emre\AppData\Local\npm-cache\_logs\2023-05-26T15_37_34_931Z-eresolve-report.txt
140 verbose exit 1
141 timing npm Completed in 2444ms
142 verbose unfinished npm timer reify 1685115455625
143 verbose unfinished npm timer reify:loadTrees 1685115455630
144 verbose unfinished npm timer idealTree:buildDeps 1685115455992
145 verbose unfinished npm timer idealTree:node_modules/eslint-config-standard-with-typescript 1685115457216
146 verbose code 1
147 error A complete log of this run can be found in: C:\Users\Emre\AppData\Local\npm-cache\_logs\2023-05-26T15_37_34_931Z-debug-0.log
```

**Comment by mightyiam** [comment]
Thank you. We'll take a look at this. Highest priority is currently #1149.

**Comment by mightyiam** [comment]
We need to upgrade our eslint-config-standard dependency. Scheduled for next Friday.

**Comment by chenbolan** [comment]
I also encountered the same problem. May I ask when the upgrade of eslint-config-standard will be completed?

**Comment by mightyiam** [comment]
Next work session is Friday. Possibly then.

**Comment by falsepopsky** [comment]
> Next work session is Friday. Possibly then.

#1175 I have already submitted a pull request for this because the other one did not receive an update. Could you please take a look whenever it is possible? Thank you.

**Comment by rostislav-simonik** [comment]
With the latest release, you can use v16
