### ISSUE TITLE
Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid

### ISSUE THREAD

**Issue by ramsey** [standard/eslint-config-standard-with-typescript#348]
**What version of this package are you using?**

- `^18.0.2`

**What operating system, Node.js, and npm version?**

- macOS 10.15.5
- Node v14.1.0
- NPM 6.14.4
- Yarn 1.22.4

**What happened?**

```
Error: .eslintrc.js » eslint-config-standard-with-typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid:
	Value {"allowString":false,"allowNumber":false,"allowNullableObject":false,"allowNullableBoolean":false,"allowNullableString":false,"allowNullableNumber":false,"allowAny":false} should NOT have additional properties.

    at validateRuleOptions (/path/to/my/project/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /path/to/my/project/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/path/to/my/project/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/path/to/my/project/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/path/to/my/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/path/to/my/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesRecursive (/path/to/my/project/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/path/to/my/project/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:49)
```

**What did you expect to happen?**

I expect `eslint` to run without invalid configuration rules.

**Are you willing to submit a pull request to fix this bug?**

Yes, but I need to make sure nothing is wrong with my configuration first. (Maybe this is user error and not a bug. 😄 )

### To Reproduce

I created a vanilla Electron app using [Electron Forge](https://www.electronforge.io/). What follows uses those setup instructions to help you quickly reproduce this.

1. `yarn create electron-app MYPROJECT --template=typescript-webpack`
2. `cd MYPROJECT`
3. `yarn add --dev eslint-plugin-standard eslint-plugin-promise eslint-plugin-node eslint-config-standard-with-typescript`
4. `rm .eslintrc.json` (remove the default eslint configuration created for you)
5. Create `.eslintrc.js`, based on the suggestion from this project's README
    ``` bash
    cat >./.eslintrc.js <<EOL
    module.exports = {
      extends: 'standard-with-typescript',
      parserOptions: {
        project: './tsconfig.json'
      }
    }
    EOL
    ```
6. Run it: `yarn lint`

You should see the error output pasted above under "What happened?"

**Comment by ramsey** [comment]
It was user error. electron-forge locks @typescript-eslint/eslint-plugin to `^2.18.0`, and this was causing the problem.

Closing.
